//! POSIX error numbers (Linux x86-64 ABI values).

/// Operation not permitted (EPERM = 1).
pub const EPERM: i32 = 1;
/// No such file or directory (ENOENT = 2).
pub const ENOENT: i32 = 2;
/// No such process (ESRCH = 3).
pub const ESRCH: i32 = 3;
/// Interrupted system call (EINTR = 4).
pub const EINTR: i32 = 4;
/// Input/output error (EIO = 5).
pub const EIO: i32 = 5;
/// No such device or address (ENXIO = 6).
pub const ENXIO: i32 = 6;
/// Argument list too long (E2BIG = 7).
pub const E2BIG: i32 = 7;
/// Exec format error (ENOEXEC = 8).
pub const ENOEXEC: i32 = 8;
/// Bad file descriptor (EBADF = 9).
pub const EBADF: i32 = 9;
/// No child processes (ECHILD = 10).
pub const ECHILD: i32 = 10;
/// Resource temporarily unavailable / try again (EAGAIN = 11).
pub const EAGAIN: i32 = 11;
/// Cannot allocate memory (ENOMEM = 12).
pub const ENOMEM: i32 = 12;
/// Permission denied (EACCES = 13).
pub const EACCES: i32 = 13;
/// Bad address (EFAULT = 14).
pub const EFAULT: i32 = 14;
/// Device or resource busy (EBUSY = 16).
pub const EBUSY: i32 = 16;
/// File exists (EEXIST = 17).
pub const EEXIST: i32 = 17;
/// Invalid cross-device link (EXDEV = 18).
pub const EXDEV: i32 = 18;
/// No such device (ENODEV = 19).
pub const ENODEV: i32 = 19;
/// Not a directory (ENOTDIR = 20).
pub const ENOTDIR: i32 = 20;
/// Is a directory (EISDIR = 21).
pub const EISDIR: i32 = 21;
/// Invalid argument (EINVAL = 22).
pub const EINVAL: i32 = 22;
/// Too many open files in system (ENFILE = 23).
pub const ENFILE: i32 = 23;
/// Too many open files (EMFILE = 24).
pub const EMFILE: i32 = 24;
/// Inappropriate I/O control operation / not a typewriter (ENOTTY = 25).
pub const ENOTTY: i32 = 25;
/// Text file busy (ETXTBSY = 26).
pub const ETXTBSY: i32 = 26;
/// File too large (EFBIG = 27).
pub const EFBIG: i32 = 27;
/// No space left on device (ENOSPC = 28).
pub const ENOSPC: i32 = 28;
/// Illegal seek (ESPIPE = 29).
pub const ESPIPE: i32 = 29;
/// Read-only file system (EROFS = 30).
pub const EROFS: i32 = 30;
/// Too many links (EMLINK = 31).
pub const EMLINK: i32 = 31;
/// Broken pipe (EPIPE = 32).
pub const EPIPE: i32 = 32;
/// Numerical result out of range (ERANGE = 34).
pub const ERANGE: i32 = 34;
/// File name too long (ENAMETOOLONG = 36).
pub const ENAMETOOLONG: i32 = 36;
/// Invalid system call / function not implemented (ENOSYS = 38).
pub const ENOSYS: i32 = 38;
