//! POSIX.1-2024 Flags and Signal Constants.

// ============================================================================
// Epoll Operation Constants and Event Flags
// ============================================================================

/// Register a target file descriptor on the epoll instance.
pub const EPOLL_CTL_ADD: i32 = 1;
/// Deregister a target file descriptor from the epoll instance.
pub const EPOLL_CTL_DEL: i32 = 2;
/// Change the event mask associated with a target file descriptor.
pub const EPOLL_CTL_MOD: i32 = 3;

/// Ready for read operations.
pub const EPOLLIN: u32 = 0x0001;
/// Exceptional condition or urgent data available for read.
pub const EPOLLPRI: u32 = 0x0002;
/// Ready for write operations.
pub const EPOLLOUT: u32 = 0x0004;
/// Error condition happened on the associated file descriptor.
pub const EPOLLERR: u32 = 0x0008;
/// Hang up happened on the associated file descriptor.
pub const EPOLLHUP: u32 = 0x0010;
/// Stream socket peer closed connection or shut down writing half.
pub const EPOLLRDHUP: u32 = 0x2000;
/// Sets Edge Triggered behavior for the associated file descriptor.
pub const EPOLLET: u32 = 1 << 31;

// ============================================================================
// File Open Flags (O_*)
// ============================================================================

/// Open file for reading only.
pub const O_RDONLY: i32 = 0x0000;
/// Open file for writing only.
pub const O_WRONLY: i32 = 0x0001;
/// Open file for reading and writing.
pub const O_RDWR: i32 = 0x0002;
/// Create file if it does not already exist.
pub const O_CREAT: i32 = 0x0040;
/// Exclusive creation: fail if file already exists.
pub const O_EXCL: i32 = 0x0080;
/// Truncate file size to 0 bytes if it exists.
pub const O_TRUNC: i32 = 0x0200;
/// Append writes to end of file.
pub const O_APPEND: i32 = 0x0400;
/// Non-blocking I/O mode.
pub const O_NONBLOCK: i32 = 0x0800;
/// Fail if the target path is not a directory.
pub const O_DIRECTORY: i32 = 0x10000;
/// Set close-on-exec flag on new file descriptor.
pub const O_CLOEXEC: i32 = 0x80000;

// ============================================================================
// File Seek Modes
// ============================================================================

/// Set file offset relative to the beginning of the file.
pub const SEEK_SET: i32 = 0;
/// Set file offset relative to the current file offset.
pub const SEEK_CUR: i32 = 1;
/// Set file offset relative to the end of the file.
pub const SEEK_END: i32 = 2;

// ============================================================================
// Memory Management Flags (mmap / mprotect)
// ============================================================================

/// Memory page cannot be accessed.
pub const PROT_NONE: i32 = 0x00;
/// Memory page can be read.
pub const PROT_READ: i32 = 0x01;
/// Memory page can be written.
pub const PROT_WRITE: i32 = 0x02;
/// Memory page can be executed.
pub const PROT_EXEC: i32 = 0x04;

/// Share memory mapping with other processes mapping the same region.
pub const MAP_SHARED: i32 = 0x01;
/// Create a private copy-on-write memory mapping.
pub const MAP_PRIVATE: i32 = 0x02;
/// Place mapping at exact virtual address specified without relocation.
pub const MAP_FIXED: i32 = 0x10;
/// Memory mapping is not backed by any file; contents are zero-initialized.
pub const MAP_ANONYMOUS: i32 = 0x20;

// ============================================================================
// Process Wait Flags (waitpid options)
// ============================================================================

/// Return immediately if no child process has exited.
pub const WNOHANG: i32 = 1;
/// Return status for stopped child processes as well.
pub const WUNTRACED: i32 = 2;
/// Return status for stopped children resumed via `SIGCONT`.
pub const WCONTINUED: i32 = 8;

// ============================================================================
// POSIX Signals (Documented Range: 1..=31)
// ============================================================================

/// Minimum valid standard POSIX signal number (1).
pub const SIG_MIN: i32 = 1;
/// Maximum valid standard POSIX signal number (31).
pub const SIG_MAX: i32 = 31;

/// Hangup detected on controlling terminal or death of controlling process.
pub const SIGHUP: i32 = 1;
/// Interrupt signal from keyboard (Ctrl+C).
pub const SIGINT: i32 = 2;
/// Quit signal from keyboard with core dump request (Ctrl+\).
pub const SIGQUIT: i32 = 3;
/// Illegal instruction executed.
pub const SIGILL: i32 = 4;
/// Trace/breakpoint trap.
pub const SIGTRAP: i32 = 5;
/// Abort signal generated by `abort()`.
pub const SIGABRT: i32 = 6;
/// Bus error (invalid memory alignment or bus fault).
pub const SIGBUS: i32 = 7;
/// Floating-point exception or integer divide-by-zero.
pub const SIGFPE: i32 = 8;
/// Kill signal (cannot be caught or ignored).
pub const SIGKILL: i32 = 9;
/// User-defined signal 1.
pub const SIGUSR1: i32 = 10;
/// Invalid memory reference / segmentation violation.
pub const SIGSEGV: i32 = 11;
/// User-defined signal 2.
pub const SIGUSR2: i32 = 12;
/// Broken pipe: write to pipe with no readers.
pub const SIGPIPE: i32 = 13;
/// Timer alarm signal from `alarm()`.
pub const SIGALRM: i32 = 14;
/// Termination signal (default polite termination request).
pub const SIGTERM: i32 = 15;
/// Stack fault on coprocessor.
pub const SIGSTKFLT: i32 = 16;
/// Child process stopped, continued, or terminated.
pub const SIGCHLD: i32 = 17;
/// Continue executing if stopped.
pub const SIGCONT: i32 = 18;
/// Stop process execution (cannot be caught or ignored).
pub const SIGSTOP: i32 = 19;
/// Terminal stop signal (Ctrl+Z).
pub const SIGTSTP: i32 = 20;
/// Background process attempting read from controlling terminal.
pub const SIGTTIN: i32 = 21;
/// Background process attempting write to controlling terminal.
pub const SIGTTOU: i32 = 22;
/// Urgent condition on socket / out-of-band data.
pub const SIGURG: i32 = 23;
/// CPU time limit exceeded.
pub const SIGXCPU: i32 = 24;
/// File size limit exceeded.
pub const SIGXFSZ: i32 = 25;
/// Virtual timer expired.
pub const SIGVTALRM: i32 = 26;
/// Profiling timer expired.
pub const SIGPROF: i32 = 27;
/// Terminal window size change signal.
pub const SIGWINCH: i32 = 28;
/// I/O now possible on asynchronous descriptor.
pub const SIGIO: i32 = 29;
/// Power failure restart.
pub const SIGPWR: i32 = 30;
/// Bad system call number invoked.
pub const SIGSYS: i32 = 31;

// Signal Dispositions

/// Default signal handling disposition.
pub const SIG_DFL: usize = 0;
/// Ignore signal disposition.
pub const SIG_IGN: usize = 1;
/// Error return from signal configuration functions.
pub const SIG_ERR: usize = !0;

// Sigaction Flags (SA_*)

/// Do not generate `SIGCHLD` when child processes stop.
pub const SA_NOCLDSTOP: u64 = 0x00000001;
/// Do not transform child processes into zombies upon termination.
pub const SA_NOCLDWAIT: u64 = 0x00000002;
/// Invoke signal-catching function with three arguments (`siginfo_t`).
pub const SA_SIGINFO: u64 = 0x00000004;
/// Signal action uses user-space restorer trampoline (`sa_restorer`).
pub const SA_RESTORER: u64 = 0x04000000;
/// Execute signal handler on alternate signal stack.
pub const SA_ONSTACK: u64 = 0x08000000;
/// Restart restartable system calls automatically when interrupted.
pub const SA_RESTART: u64 = 0x10000000;
/// Do not prevent the signal from being received from within its own handler.
pub const SA_NODEFER: u64 = 0x40000000;
/// Reset signal disposition to `SIG_DFL` upon entry to handler.
pub const SA_RESETHAND: u64 = 0x80000000;

// Sigprocmask Actions

/// Add the specified signals to the current signal mask.
pub const SIG_BLOCK: i32 = 0;
/// Remove the specified signals from the current signal mask.
pub const SIG_UNBLOCK: i32 = 1;
/// Replace the current signal mask with the specified signal set.
pub const SIG_SETMASK: i32 = 2;

// ============================================================================
// POSIX File Mode Types (S_IF*) and Permissions
// ============================================================================

/// Bitmask for file type bitfield in `st_mode`.
pub const S_IFMT: u32 = 0o170000;
/// Socket file type.
pub const S_IFSOCK: u32 = 0o140000;
/// Symbolic link file type.
pub const S_IFLNK: u32 = 0o120000;
/// Regular file type.
pub const S_IFREG: u32 = 0o100000;
/// Block special device file type.
pub const S_IFBLK: u32 = 0o060000;
/// Directory file type.
pub const S_IFDIR: u32 = 0o040000;
/// Character special device file type.
pub const S_IFCHR: u32 = 0o020000;
/// FIFO / named pipe special file type.
pub const S_IFIFO: u32 = 0o010000;

// Special Mode Bits (Set-UID, Set-GID, Sticky)

/// Set user ID on execution (`0o4000`).
pub const S_ISUID: u32 = 0o4000;
/// Set group ID on execution (`0o2000`).
pub const S_ISGID: u32 = 0o2000;
/// Sticky bit (`0o1000`).
pub const S_ISVTX: u32 = 0o1000;

// Permission Bits

/// Read, write, and execute permissions for file owner (`0o700`).
pub const S_IRWXU: u32 = 0o700;
/// Read permission for file owner (`0o400`).
pub const S_IRUSR: u32 = 0o400;
/// Write permission for file owner (`0o200`).
pub const S_IWUSR: u32 = 0o200;
/// Execute/search permission for file owner (`0o100`).
pub const S_IXUSR: u32 = 0o100;

/// Read, write, and execute permissions for file group (`0o070`).
pub const S_IRWXG: u32 = 0o070;
/// Read permission for file group (`0o040`).
pub const S_IRGRP: u32 = 0o040;
/// Write permission for file group (`0o020`).
pub const S_IWGRP: u32 = 0o020;
/// Execute/search permission for file group (`0o010`).
pub const S_IXGRP: u32 = 0o010;

/// Read, write, and execute permissions for others (`0o007`).
pub const S_IRWXO: u32 = 0o007;
/// Read permission for others (`0o004`).
pub const S_IROTH: u32 = 0o004;
/// Write permission for others (`0o002`).
pub const S_IWOTH: u32 = 0o002;
/// Execute/search permission for others (`0o001`).
pub const S_IXOTH: u32 = 0o001;

// ============================================================================
// Directory Entry Types (DT_*)
// ============================================================================

/// Unknown directory entry type.
pub const DT_UNKNOWN: u8 = 0;
/// Named pipe / FIFO directory entry type.
pub const DT_FIFO: u8 = 1;
/// Character device directory entry type.
pub const DT_CHR: u8 = 2;
/// Directory directory entry type.
pub const DT_DIR: u8 = 4;
/// Block device directory entry type.
pub const DT_BLK: u8 = 6;
/// Regular file directory entry type.
pub const DT_REG: u8 = 8;
/// Symbolic link directory entry type.
pub const DT_LNK: u8 = 10;
/// UNIX domain socket directory entry type.
pub const DT_SOCK: u8 = 12;

// ============================================================================
// Terminal Flags (termios)
// ============================================================================

/// Echo input characters back to terminal.
pub const ECHO: u32 = 0x0008;
/// Enable canonical input mode (line-buffered with line editing).
pub const ICANON: u32 = 0x0002;
/// Enable generation of signals on special control characters (INTR, QUIT, SUSP).
pub const ISIG: u32 = 0x0001;

// ============================================================================
// Audit Journal Event Types
// ============================================================================

/// Audit event: user interactive action executed.
pub const AUDIT_TYPE_USER_ACTION: u32 = 1;
/// Audit event: new process spawned.
pub const AUDIT_TYPE_PROCESS_SPAWN: u32 = 2;
/// Audit event: process terminated.
pub const AUDIT_TYPE_PROCESS_EXIT: u32 = 3;
/// Audit event: file created.
pub const AUDIT_TYPE_FILE_CREATE: u32 = 4;
/// Audit event: file contents modified.
pub const AUDIT_TYPE_FILE_MODIFY: u32 = 5;
/// Audit event: file unlinked/deleted.
pub const AUDIT_TYPE_FILE_UNLINK: u32 = 6;
/// Audit event: directory created.
pub const AUDIT_TYPE_DIR_CREATE: u32 = 7;
/// Audit event: working directory changed.
pub const AUDIT_TYPE_DIR_CHANGE: u32 = 8;
/// Audit event: audit system snapshot captured.
pub const AUDIT_TYPE_SNAPSHOT_CREATED: u32 = 9;
/// Audit event: security alert or policy violation.
pub const AUDIT_TYPE_SECURITY_ALERT: u32 = 10;

// ============================================================================
// System V AMD64 ELF Auxiliary Vector Types (AT_*)
// ============================================================================

/// End of auxiliary vector marker.
pub const AT_NULL: u64 = 0;
/// Entry should be ignored.
pub const AT_IGNORE: u64 = 1;
/// File descriptor of the executable program.
pub const AT_EXECFD: u64 = 2;
/// Virtual address of program headers in memory.
pub const AT_PHDR: u64 = 3;
/// Size of each ELF program header entry in bytes.
pub const AT_PHENT: u64 = 4;
/// Total number of program header entries.
pub const AT_PHNUM: u64 = 5;
/// System memory page size in bytes (4096 on x86_64).
pub const AT_PAGESZ: u64 = 6;
/// Base virtual load address of dynamic interpreter/linker.
pub const AT_BASE: u64 = 7;
/// Architecture / kernel execution flags.
pub const AT_FLAGS: u64 = 8;
/// Virtual entry point address of program executable.
pub const AT_ENTRY: u64 = 9;
